apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ed4d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ed4d
    app.kubernetes.io/part-of: tkwch-fix-0075-0003-app
  name: devfile-sample-ed4d
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ed4d
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ed4d
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0003-tenant/tkwch-fix-0075-0003-app/devfile-sample-ed4d@sha256:c54200785d239e6d8b9deaca945dc0b0e1ab5266b5ac2a2a2b4f6b931ea0e696
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
